version: "1.0.0"

training:
  epsilon_fn:
      initial_learning_rate: 0.9 # Initial learning rate
      decay_steps: 25000         # Number of steps to decay the learning rate
      end_learning_rate: 0.01
  optimizer:
    learning_rate: 0.0006
  gamma: 0.98
  target_update_period: 2000
  iterations: 200000
  collect_steps_per_iteration: 16
  initial_dataset_size: 50000

env:
  discount_factor: 0.98
